{% extends embebed ? "embebed.html" : "layout.html" %}

{% block content %}
<div class="wrap-grid100 p-l-100 p-r-1000 p-t-77 p-b-30">
            <h1>{{ titulo }}</h1>
            <div class="form-row align-content-lg-center">
                <div class="col-lg-3 col-md-4"></div>
                <div class="col-lg-6 col-md-4" >
                <form action="{{ accion }}" method="POST" enctype="multipart/form-data">
                    {% for dataform in textos %}
                    <div class="form-group">
                        <label for="{{ dataform.id }}">{{ dataform.label }}</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa {{ dataform.icono}}"></i>
                                </div>
                            </div>
                            <input id="{{ dataform.id }}" name="{{ dataform.id }}" placeholder="{{ dataform.label }}" type="text" required="required" class="form-control">
                        </div>
                    </div>
                    {% endfor %}
                    {% for dataform in combos %}
                    <div class="form-group">
                        <label for="{{ dataform.id }}">{{ dataform.label }}</label>
                        <div>
                            <select id="{{ dataform.id }}" name="{{ dataform.id }}" aria-describedby="{{ dataform.id }}HelpBlock" required="required" class="custom-select">
                                <option value="" selected="selected">Seleccione...</option>
                                {% for item in dataform.combo %}
                                <option value="{{ item.id }}" >{{ item.name}}</option>
                                {% endfor %}
                            </select>
                            <span id="{{ dataform.id }}HelpBlock" class="form-text text-muted">{{ dataform.label }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <button name="submit" type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                </div>
                <div class="col-lg-3 col-md-4"></div>
            </div>
        </div>
<script>
    $(document).ready(function() {
        $('form').submit(function(event) {

            // get the form data
            // there are many ways to get this data using jQuery (you can use the class or id also)
            var formData = $(this).serialize();

            // process the form
            $.ajax({
                type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                url         : $(this).attr('action'), // the url where we want to POST
                data        : formData, // our data object
                dataType    : 'json', // what type of data do we expect back from the server
                encode          : true
            })
            // using the done promise callback
                .done(function(data) {

                    // log data to the console so we can see
                    console.log(data);
                    alert({{back}});
                    //location.href = '{{back}}';
                });

            // stop the form from submitting the normal way and refreshing the page
            event.preventDefault();
        });

    });
</script>
{% endblock %}
