{% extends "layout.html" %}

{% block content %}
<div class="wrap-grid100 p-l-20 p-r-20 p-t-77 p-b-30">
    <div class="row">
        <div class="col-12 align-content-lg-center">
            <div class="text-center">
                <div class="row">
                    <div class="col-md-10 text-center">
                        <span class="h3">{{ titulo }}</span>
                    </div>
                    <div class="col-md-2">
                        <span>
                        {% if linkAdd %}
                            <a href=" {{ linkAdd }}"><button class="btn btn-xs btn-outline-success " > <i class="fa fa-plus-circle"></i> Nuevo</button></a>
                        {% endif %}
                        </span>
                    </div>
                </div>
            </div>
            <br>
            <div>
                <table id="grid-data-api" class="table table-condensed table-hover table-striped" >
                    <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Cliente</th>
                        <th>Producto</th>
                        <th>Origen</th>
                        <th>Actualizacion</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if datos %}
                    {% for dato in datos.rows %}
                    <tr>
                        <td>{{ dato.fecha }}</td>
                        <td>{{ dato.cliente }}</td>
                        <td>{{ dato.producto }}</td>
                        <td>{{ dato.origen }}</td>
                        <td>{{ dato.actualizacion }}</td>
                        <td>{{ dato.estado }}</td>
                        <td>
                            <a href="/reclamo/{{dato.id}}/ver" class="btn btn-xs btn-primary help" data-toggle="tooltip" data-placement="top" title="Ver Reclamo" ><i class="fa fa-eye"></i></a>
                            {% for flu in flujo %}
                            {% if dato.idestado == flu.id %}
                            {% if flu.idevento_new == 4 and dato.dictamen == null %}
                            <a href="/reclamo/{{dato.id}}/diag" class="btn btn-xs btn-outline-danger help" data-toggle="tooltip" data-placement="top" title="Analizar Reclamo" >
                                <i class="fa fa-bug" ></i>
                            </a>
                            {% endif %}
                            {% if flu.idevento_new == 7 %}
                            <a href="/reclamo/{{dato.id}}/notif" class="btn btn-xs btn-outline-info help" data-toggle="tooltip" data-placement="top" title="Cliente Notificado" ><i class="fa fa-send-o"></i></a>
                            {% endif %}
                            {% if flu.idevento_new == 5 %}
                            <a href="/reclamo/{{dato.id}}/envio" class="btn btn-xs btn-outline-warning help" data-toggle="tooltip" data-placement="top" title="Envio Caja"><i class="fa fa-truck"></i></a>
                            {% endif %}
                            {% if flu.idevento_new == 6 %}
                            <a href="/reclamo/{{dato.id}}/recepcion" class="btn btn-xs btn-outline-primary help " data-toggle="tooltip" data-placement="top" title="Recepcion de Caja"><i class="fa fa-gift"></i></a>
                            {% endif %}
                            {% if flu.idevento_new == 8 %}
                            <a href="/reclamo/{{dato.id}}/resolucion" class="btn btn-xs btn-outline-success help" data-toggle="tooltip" data-placement="top" title="Resolucion de  Reclamo"><i class="fa fa-check-square-o"></i></a>
                            {% endif %}
                            {% if flu.idevento_new == 9 %}
                            <a href="/reclamo/{{dato.id}}/anulacion" class="btn btn-xs btn-outline-dark help" data-toggle="tooltip" data-placement="top" title="Anulacion Reclamo"><i class="fa fa-ban"></i></a>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<div class="modal-container"></div>
<script>
    $(document).ready(function () {
        $(".help").tooltip();
    })
</script>
</div>
{% endblock %}