DROP TABLE IF EXISTS flujo_eventos;
CREATE TABLE IF NOT EXISTS flujo_eventos(
                                            idmaquinaestados INTEGER  NOT NULL PRIMARY KEY
    ,idevento_old     INTEGER  NOT NULL
    ,idevento_new     INTEGER  NOT NULL
);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (1,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (2,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (3,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (4,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (5,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (7,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (8,1,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (1,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (2,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (3,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (4,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (5,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (7,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (8,3,2);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (1,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (2,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (3,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (4,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (5,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (7,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (8,1,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (1,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (2,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (3,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (4,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (5,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (7,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (8,2,3);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,1,4);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,7,4);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,7,5);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,5,6);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,1,7);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,4,7);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,5,7);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,6,7);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,1,8);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,4,8);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,6,8);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,7,8);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,1,9);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,4,9);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,5,9);
INSERT INTO flujo_eventos(idmaquinaestados,idevento_old,idevento_new) VALUES (6,7,9);