{% extends "layout.html" %}

{% block content %}
<div class="wrap-grid100 p-l-100 p-r-1000 p-t-77 p-b-30">
            <div class="align-content-center">
                <h1>Configuracion de Estado</h1>
                <h2>Tabla:{{maquinaestados.name}} en el evento de {{eventos.name}}</h2>
            </div>
            <div class="form-row align-content-lg-center">
                <div class="col-lg-3 col-md-4"></div>
                <div class="col-lg-6 col-md-4" >
                <form action="/estado" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="name">Nombre</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-user-circle"></i>
                                </div>
                            </div>
                            <input id="name" name="name" placeholder="Nombre" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-4">Aplica</label>
                        <div class="col-8">
                            <div class="custom-control custom-radio custom-control-inline">
                                <input name="aplica" id="aplica_0" type="radio" class="custom-control-input" value="1">
                                <label for="aplica_0" class="custom-control-label">Si</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input name="aplica" id="aplica_1" type="radio" class="custom-control-input" value="0">
                                <label for="aplica_1" class="custom-control-label">No</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="submit" type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                    <input id="idmaquinaestado" name="idmaquinaestado" type="hidden" value="{{ maquinaestados.id }}" >
                    <input id="idevento" name="idevento" type="hidden" value="{{ eventos.id }}" >
                </form>
                </div>
                <div class="col-lg-3 col-md-4"></div>
            </div>
</div>
<script>
    $(document).ready(function() {
        $('form').submit(function(event) {

            // get the form data
            // there are many ways to get this data using jQuery (you can use the class or id also)
            var formData = $(this).serialize();

            // process the form
            $.ajax({
                type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                url         : $(this).attr('action'), // the url where we want to POST
                data        : formData, // our data object
                dataType    : 'json', // what type of data do we expect back from the server
                encode          : true
            })
            // using the done promise callback
                .done(function(data) {

                    // log data to the console so we can see
                    console.log(data);
                    if(!(data.urlCallBack===undefined)){
                        location.href = data.urlCallBack;
                    }
                });

            // stop the form from submitting the normal way and refreshing the page
            event.preventDefault();
        });

    });
</script>
{% endblock %}
