<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>{{ titulo }}</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/bootgrid/jquery.bootgrid.css">
        <link rel="stylesheet" href="/bootstrap/font-awesome/css/all.css">

        <script src="/jquery/jquery.js" ></script>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/bootgrid/jquery.bootgrid.js" ></script>
        <script src="/bootgrid/jquery.bootgrid.fa.js" ></script>
    </head>
    <body>
        <div class="container-fluid align-content-center">
            <h1>{{ titulo }}</h1>
            <div class="form-row align-content-lg-center">
                <div class="col-lg-3 col-md-4"></div>
                <div class="col-lg-6 col-md-4" >
                <form action="/producto" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="apelnom">Nombre</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-user-circle"></i>
                                </div>
                            </div>
                            <input id="name" name="name" placeholder="Nombre" type="text" required="required" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="idtipoproducto">Tipo Producto</label>
                        <div>
                            <select id="idtipoproducto" name="idtipoproducto" aria-describedby="tipoprodHelpBlock" required="required" class="custom-select">
                                {% for item in tipoprod %}
                                    <option value="{{ item.id }}">{{ item.nombre}}</option>
                                {% endfor %}
                            </select>
                            <span id="tipoprodHelpBlock" class="form-text text-muted">Tipo de Producto</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="submit" type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                </div>
                <div class="col-lg-3 col-md-4"></div>
            </div>
        </div>
    </body>
</html>
