<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/jquery/bootgrid/jquery.bootgrid.css">
        <link rel="stylesheet" href="/bootstrap/font-awesome/css/all.css">

        <script src="/jquery/jquery.js" ></script>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/jquery/bootgrid/jquery.bootgrid.js" ></script>
        <script src="/jquery/bootgrid/jquery.bootgrid.fa.js" ></script>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Agregar Proceso</h1>
        <form action="/proceso" method="POST" enctype="multipart/form-data">
                <label>Nombre</label>
                <input type="text" value="" name="name"/>
                <br/>
                <label>Macro proceso</label>
                <select name="idmacroproceso">
                    <?php foreach ($macroprocesos as $i):?>
                        <option value="<?= $i->id?>"><?=$i->name?></option>
                    <?php endforeach;?>
                </select>
                <br/>
                <label>Responsable</label>
            <select name="idresponsable">
                <?php foreach ($responsables as $i):?>
                    <option value="<?= $i->id?>"><?=$i->name?></option>
                <?php endforeach;?>
            </select>
                <br/>
                <input type="submit" class="btn btn-outline-success" name="Enviar" value="Grabar"/>
        </form>
    </body>
</html>
