<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>{{ titulo }}</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/bootgrid/jquery.bootgrid.css">
        <link rel="stylesheet" href="/bootstrap/font-awesome/css/all.css">

        <script src="/jquery/jquery.js" ></script>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/bootgrid/jquery.bootgrid.js" ></script>
        <script src="/bootgrid/jquery.bootgrid.fa.js" ></script>
    </head>
    <body>
        <div class="container-fluid align-content-center">
            <h1>{{ titulo }}</h1>
            <div class="form-row align-content-lg-center">
                <div class="col-lg-3 col-md-4"></div>
                <div class="col-lg-6 col-md-4" >
                <form action="/tipoproducto" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="apelnom">Nombre</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-user-circle"></i>
                                </div>
                            </div>
                            <input id="name" name="name" placeholder="Nombre" type="text" required="required" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="submit" type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                </div>
                <div class="col-lg-3 col-md-4"></div>
            </div>
        </div>
    <script>
        $(document).ready(function() {
            $('form').submit(function(event) {

                // get the form data
                // there are many ways to get this data using jQuery (you can use the class or id also)
                var formData = $(this).serialize();

                // process the form
                $.ajax({
                    type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                    url         : $(this).attr('action'), // the url where we want to POST
                    data        : formData, // our data object
                    dataType    : 'json', // what type of data do we expect back from the server
                    encode          : true
                })
                // using the done promise callback
                    .done(function(data) {

                        // log data to the console so we can see
                        console.log(data);
                        if(!(data.urlCallBack===undefined)){
                            location.href = data.urlCallBack;
                        }
                    });

                // stop the form from submitting the normal way and refreshing the page
                event.preventDefault();
            });

        });
    </script>
    </body>
</html>
