{% extends "layout.html" %}

{% block content %}
<div class="wrap-login100 p-l-100 p-r-50 p-t-77 p-b-30">
    <form class="login100-form validate-form">
                        <span class="login100-form-title p-b-55">
                            Ingresar
                        </span>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
            <input class="input100" type="text" name="email" placeholder="Email">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                                <span class="lnr lnr-envelope"></span>
                            </span>
        </div>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Contraseña requerida">
            <input class="input100" type="password" name="pass" placeholder="Contraseña">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                                <span class="lnr lnr-lock"></span>
                            </span>
        </div>

        <div class="container-login100-form-btn p-t-25">
            <button class="login100-form-btn">
                Ingresar
            </button>
        </div>

        <div class="text-center w-full p-t-42 p-b-22">
                            <span class="txt1">
                                O Ingresar usando
                            </span>
        </div>

        <a href="#" class="btn-face m-b-10">
            <i class="fa fa-facebook-official"></i>
            Facebook
        </a>

        <a href="#" class="btn-google m-b-10">
            <img src="./images/icons/icon-google.png" alt="GOOGLE">
            Google
        </a>

        <div class="text-center w-full p-t-115">
                            <span class="txt1">
                                Te olvidaste la contraseña?
                            </span>

            <a class="txt1 bo1 hov1" href="/registrar">
                Registrate
            </a>
        </div>
    </form>
</div>
{% endblock %}