{% extends "layout.html" %}

{% block content %}
<div class="wrap-login100 p-l-100 p-r-50 p-t-77 p-b-30">
    <form class="login100-form validate-form" method="post" action="/api/v1/user/login">
        <span class="login100-form-title p-b-55">
            Ingresar
        </span>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
            <input class="input100" type="text" name="usuario" placeholder="Email">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
            <span class="lnr lnr-envelope"></span>
            </span>
        </div>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Contraseña requerida">
            <input class="input100" type="password" name="password" placeholder="Contraseña">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                                <span class="lnr lnr-lock"></span>
                            </span>
        </div>

        <div class="container-login100-form-btn p-t-25">
            <button class="login100-form-btn">
                Ingresar
            </button>
        </div>

        <div class="text-center w-full p-t-42 p-b-22">
                            <span class="txt1">
                                O Ingresar usando
                            </span>
        </div>

        <a href="#" class="btn-face m-b-10">
            <i class="fa fa-facebook-official"></i>
            Facebook
        </a>

        <a href="#" class="btn-google m-b-10">
            <img src="./images/icons/icon-google.png" alt="GOOGLE">
            Google
        </a>

        <div class="text-center w-full p-t-115">
                            <span class="txt1">
                                Te olvidaste la contraseña?
                            </span>

            <a class="txt1 bo1 hov1" href="/registrar">
                Registrate
            </a>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('form').submit(function(event) {

            // get the form data
            // there are many ways to get this data using jQuery (you can use the class or id also)
            var formData = JSON.stringify($(this).serializeFormJSON());

            //alert(JSON.stringify(formData));
            //event.preventDefault();
            // process the form
            $.ajax({
                type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                contentType : "application/json",
//                headers:{
//                    "Authorization": "Bearer " + btoa(username + ":" + password)
//                },
                url         : $(this).attr('action'), // the url where we want to POST
                data        : formData, // our data object
                dataType    : 'json', // what type of data do we expect back from the server
                encode          : true
            })
            // using the done promise callback
                .done(function(data) {
                    // log data to the console so we can see
                    console.log(data);
                    if(!(data.codigo===undefined)){
                        if(data.codigo==0){
                            var param = $.base64.encode(JSON.stringify(data.respuesta));
                            location.href = '/login/ok/' + param;
                        }else{
                            location.href = '/error/'+data.codigo;
                        }
                    }
                });

            // stop the form from submitting the normal way and refreshing the page
            event.preventDefault();
        });
    });
    $.fn.serializeFormJSON = function () {
        var o = {};
        var a = this.serializeArray();
        $.each(a, function () {
            if (o[this.name]) {
                if (!o[this.name].push) {
                    o[this.name] = [o[this.name]];
                }
                o[this.name].push(this.value || '');
            } else {
                o[this.name] = this.value || '';
            }
        });
        return o;
    };
</script>
{% endblock %}