{% extends "layout.html" %}

{% block content %}
<div class="wrap-login100 p-l-100 p-r-50 p-t-77 p-b-30">
    <form class="login100-form validate-form" method="post" action="/api/v1/user/registrar">
                        <span class="login100-form-title p-b-55">
                            Ingresar
                        </span>

        <div class="wrap-input100 validate-input m-b-16" >
            <input class="input100" type="text" name="nombre" placeholder="Nombre">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                <span class="lnr lnr-user"></span>
            </span>
        </div>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
            <input class="input100" type="text" name="email" placeholder="Email">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                                <span class="lnr lnr-envelope"></span>
                            </span>
        </div>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Contraseña requerida">
            <input class="input100" type="password" name="password" placeholder="Contraseña">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                                <span class="lnr lnr-lock"></span>
                            </span>
        </div>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Contraseña requerida">
            <input class="input100" type="password" name="pass1" placeholder="Repetir Contraseña">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                                <span class="lnr lnr-lock"></span>
                            </span>
        </div>

        <div class="container-login100-form-btn p-t-25">
            <button class="login100-form-btn" type="submit">
                Crear
            </button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('form').submit(function(event) {

            // get the form data
            // there are many ways to get this data using jQuery (you can use the class or id also)
            var formData = $(this).serialize();

            // process the form
            $.ajax({
                type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                url         : $(this).attr('action'), // the url where we want to POST
                data        : formData, // our data object
                dataType    : 'json', // what type of data do we expect back from the server
                encode          : true
            })
            // using the done promise callback
                .done(function(data) {

                    // log data to the console so we can see
                    console.log(data);
                    if(!(data.codigo===undefined)){
                        if(data.codigo==0){
                            location.href = '/reclamos/tablero';
                        }else{
                            location.href = '/error/'+data.codigo;
                        }
                    }
                });

            // stop the form from submitting the normal way and refreshing the page
            event.preventDefault();
        });
    });
</script>
{% endblock %}